version: '3'

services:
  helix.swarm:
    image: perforce/helix-swarm
    hostname: helix-swarm
    container_name: helix-swarm
    domainname: helix
    restart: unless-stopped
    volumes:
      - ./data/helix-swarm:/opt/perforce/swarm/data
      - ./data/www:/var/www
      - ./data/www/html:/var/www/html
    environment:
      - P4D_PORT=<YOUR_P4PORT> # e.g. ssl:192.168.1.10:1666
      
      # Superuser and swarm user must not use the Helix Authentication Service :
      # https://www.perforce.com/manuals/swarm-admin/Content/Swarm/setup.dependencies.
      - P4D_SUPER=<YOUR_SUPER_USER>
      - P4D_SUPER_PASSWD=<YOUR_SUPER_USER_PWD>
      - SWARM_USER=<YOUR_SWARM_SUPER_USER>
      - SWARM_PASSWD=<YOUR_SWARM_SUPER_USER_PWD>

      # Your server ip / host name to be accessible by Helix Core server (e.g 192.168.1.101).
      - SWARM_HOST=<YOUR_SWARM_HOSTNAME>

      # If set to 'y', then extensions will be installed even if they already
      # exist, overwriting existing configuration.
      - SWARM_FORCE_EXT=y
    ports:
      - 80:80
      - 443:443
    working_dir: /opt/perforce/swarm
    depends_on:
      - helix.redis
    tty: false


  helix.redis:
    image: greenbone/redis-server
    hostname: helix-redis
    container_name: helix-redis
    domainname: helix
    restart: unless-stopped
    user: root
    command: redis-server --protected-mode no --port 7379 --appendonly yes
    volumes:
      - ./data/redis:/data