version: '3.8'

volumes:
  storage: {}
  logs: {}

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '4000:3000'
    volumes:
      - storage:/var/lib/grafana
      - logs:/var/log/grafana